In [1]:
import numpy as np
x = np.arange(12, 38)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [2]:
import numpy as np
arr = np.ones((5,5))
print("Original array:")
print(arr)
print("1 on the border and 0 inside in the array")
arr[1:-1,1:-1] = 0
print(arr)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
import numpy as np
arr1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",arr1)
arr2 = [0, 40]
print("Array2: ",arr2)
print("Compare each element of array1 and array2")
print(np.in1d(arr1, arr2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


In [4]:
import numpy as np
arr1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",arr1)
arr2 = [10, 30, 40, 50, 70, 90]
print("Array2: ",arr2)
print("Set difference between two arrays:")
print(np.setdiff1d(arr1, arr2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]


In [5]:

import numpy as np
arr =  np.diagflat([4, 5, 6, 8])
print(arr)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
